server:
  port: ${PORT:8089}
  
eureka:
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
          
management:
  endpoints:
    web:
      exposure:
        include: refresh, info, health, metrics, trace
  endpoint:
    health:
      show-details: ALWAYS

info:
  version: '@project.version@'

logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: DEBUG
    es.gincol.blog: DEBUG
          
swagger:
  basepackage: es.gincol.blog