server:
  port: ${PORT:8089}
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
          - env
  endpoint:
    health:
      show-details: ALWAYS

variable:
  changing: muy cambiadasssss

logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: DEBUG
    es.gincol.blog: DEBUG
          
swagger:
  basepackage: es.gincol.blog